# Winning Jeopardy
We will be using a dataset of jeopardy questions to figure out patterns in the questions to help you when

The data set can be downloaded from [here](https://www.reddit.com/r/datasets/comments/1uyd0t/200000_jeopardy_questions_in_a_json_file/)

In [48]:
import pandas as pd

jeopardy = pd.read_csv('jeopardy.csv')
jeopardy.head(5)

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams

In [49]:
jeopardy.columns

Index(['Show Number', ' Air Date', ' Round', ' Category', ' Value',
       ' Question', ' Answer'],
      dtype='object')

In [50]:
jeopardy.columns = ['Show Number', 'Air Date', 'Round', 'Category', 'Value',
       'Question', 'Answer']

In [51]:
jeopardy.columns

Index(['Show Number', 'Air Date', 'Round', 'Category', 'Value', 'Question',
       'Answer'],
      dtype='object')

# Normalizing Text

In [52]:
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub('[^A-za-z0-9\s]','',text) # remove A-Z, a-z and 0-9 from the string
    return text

In [53]:
jeopardy['clean_question'] = jeopardy['Question'].apply(normalize_text)
jeopardy['clean_answer'] = jeopardy['Answer'].apply(normalize_text)
jeopardy.head(10)

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams
5,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$200,"In the title of an Aesop fable, this insect sh...",the ant,in the title of an aesop fable this insect sha...,the ant
6,4680,2004-12-31,Jeopardy!,HISTORY,$400,Built in 312 B.C. to link Rome & the South of ...,the Appian Way,built in 312 bc to link rome the south of ita...,the appian way
7,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$400,"No. 8: 30 steals for the Birmingham Barons; 2,...",Michael Jordan,no 8 30 steals for the birmingham barons 2306 ...,michael jordan
8,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$400,"In the winter of 1971-72, a record 1,122 inche...",Washington,in the winter of 197172 a record 1122 inches o...,washington
9,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$400,This housewares store was named for the packag...,Crate & Barrel,this housewares store was named for the packag...,crate barrel

# Normalizing columns

In [54]:
def normalize_values(text):
    text = re.sub('[^A-za-z0-9\s]','',text) # remove A-Z, a-z and 0-9 from the string
    try:
        text = int(text)
    except Exception:
        text = 0
    return text

In [55]:
jeopardy['clean_value'] = jeopardy['Value'].apply(normalize_values)
jeopardy.head(10)

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200
5,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$200,"In the title of an Aesop fable, this insect sh...",the ant,in the title of an aesop fable this insect sha...,the ant,200
6,4680,2004-12-31,Jeopardy!,HISTORY,$400,Built in 312 B.C. to link Rome & the South of ...,the Appian Way,built in 312 bc to link rome the south of ita...,the appian way,400
7,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$400,"No. 8: 30 steals for the Birmingham Barons; 2,...",Michael Jordan,no 8 30 steals for the birmingham barons 2306 ...,michael jordan,400
8,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$400,"In the winter of 1971-72, a record 1,122 inche...",Washington,in the winter of 197172 a record 1122 inches o...,washington,400
9,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$400,This housewares store was named for the packag...,Crate & Barrel,this housewares store was named for the packag...,crate barrel,400

In [56]:
jeopardy['Air Date'] = pd.to_datetime(jeopardy['Air Date'])
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200

In [57]:
jeopardy.dtypes

Show Number                int64
Air Date          datetime64[ns]
Round                     object
Category                  object
Value                     object
Question                  object
Answer                    object
clean_question            object
clean_answer              object
clean_value                int64
dtype: object

# Answers in Questions

In [58]:
# Create a function that counts how often the answer is deducible from the question
def count_matches(row):
    split_answer = row['clean_answer'].split(' ')
    split_question = row['clean_question'].split(' ')
    match_count = 0
    if 'the' in split_answer:
        split_answer.remove('the')
    if len(split_answer) == 0:
        return 0
    for item in split_answer:
        if item in split_question:
            match_count += 1
    matches = match_count / len(split_answer)
    return matches

In [59]:
jeopardy['answer_in_question'] = jeopardy.apply(count_matches, axis=1)

In [60]:
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,answer_in_question
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200,0.0
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200,0.0
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200,0.0
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200,0.0
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200,0.0

In [61]:
jeopardy['answer_in_question'].mean()

0.06049325706933587

The answer will occur in the question about 6% of the time which means that we can't guess the question by hearing the answer.  We will need to study (which is what Ken Jennings did)

# Recycled questions

In [62]:
question_overlap = []
terms_used = set()

jeopardy = jeopardy.sort_values('Air Date')

In [63]:
for i, row in jeopardy.iterrows():
    split_question = row['clean_question'].split(' ')
    split_question = [q for q in split_question if len(q) > 5] # if characters are greater than 5 keep
    match_count = 0
    for word in split_question:
        if word in terms_used:
            match_count += 1
    for word in split_question:
        terms_used.add(word)
    if len(split_question) > 0:
        match_count /= len(split_question)
    question_overlap.append(match_count)
jeopardy['question_overlap'] = question_overlap
jeopardy['question_overlap'].mean()

0.6877553147640064

This means that roughly 70% of questions are recyled but these are only in terms of single words not phrases.  Plus this also looks at a small subset of questions.  This means that we do need to look into recycled questions some more.

# Low value vs high value questions

In [64]:
def determine_value(row):
    if row['clean_value'] > 800:
        value = 1
    else:
        value = 0
    return value

jeopardy['high_value'] = jeopardy.apply(determine_value, axis=1)
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,answer_in_question,question_overlap,high_value
19325,10,1984-09-21,Final Jeopardy!,U.S. PRESIDENTS,None,"Adventurous 26th president, he was 1st to ride...",Theodore Roosevelt,adventurous 26th president he was 1st to ride ...,theodore roosevelt,0,0.0,0.0,0
19301,10,1984-09-21,Double Jeopardy!,LABOR UNIONS,$200,Notorious labor leader missing since '75,Jimmy Hoffa,notorious labor leader missing since 75,jimmy hoffa,200,0.0,0.0,0
19302,10,1984-09-21,Double Jeopardy!,1789,$200,"Washington proclaimed Nov. 26, 1789 this first...",Thanksgiving,washington proclaimed nov 26 1789 this first n...,thanksgiving,200,0.0,0.0,0
19303,10,1984-09-21,Double Jeopardy!,TOURIST TRAPS,$200,Both Ferde Grofe' & the Colorado River dug thi...,the Grand Canyon,both ferde grofe the colorado river dug this ...,the grand canyon,200,0.0,0.5,0
19304,10,1984-09-21,Double Jeopardy!,LITERATURE,$200,"Depending on the book, he could be a ""Jones"", ...",Tom,depending on the book he could be a jones a sa...,tom,200,0.0,0.0,0

In [66]:
def count_usage(term):
    low_count = 0
    high_count = 0
    
    for i, row in jeopardy.iterrows():
        split_question = row['clean_question'].split(' ')
        if term in split_question:
            if row['high_value'] == 1:
                high_count += 1
            else:
                low_count += 1
    return high_count, low_count

observed_expected = []
comparison_terms = list(terms_used)[:5] # first 5 characters
observed_expected = []
for term in comparison_terms:
    observed_expected.append(count_usage(term))

observed_expected

[(2, 1), (0, 1), (8, 16), (2, 0), (0, 1)]

In [67]:
comparison_terms

['carole', 'binoche', 'taylor', 'unconstitutional', 'alkaloids']

In [68]:
terms_used

{'carole',
 'binoche',
 'taylor',
 'unconstitutional',
 'alkaloids',
 'dwarfs',
 'agencys',
 'fossilized',
 'lobstersthese',
 'hazelwood',
 'asheville',
 'prince',
 'perceived',
 'labels',
 'marital',
 'porters',
 'cinnamon',
 'phases',
 'additions',
 'automatons',
 'myungbak',
 'hirofumi',
 'grabbed',
 'niccolo',
 'satirizes',
 'gazing',
 'pyramid',
 'collaborator',
 'conqueror',
 'detachable',
 'kefauver',
 'selections',
 'confederacy',
 'authored',
 'turbulent',
 'sarawak',
 'funicello',
 'blanks',
 'alongthis',
 'language',
 'dripper',
 'haines',
 'hawked',
 'makers',
 'marples',
 'affliction',
 'stringbending',
 'sprats',
 'refuse',
 'aspects',
 'greeny',
 'pendragon',
 'hrefhttpwwwjarchivecommedia20060601_j_03jpg',
 'rangifer',
 'hrefhttpwwwjarchivecommedia20080404_dj_11wmvalex',
 'melange',
 'partial',
 'blamed',
 'genuflect',
 'selassie',
 'caliph',
 'pumpers',
 'facing',
 'institutes',
 'pumper',
 'dorian',
 'embryo',
 'enshrined',
 'flashbacks',
 'citium',
 'salina',
 'theyll',
 'tortilla',
 'stations',
 'shoreline',
 'genesis',
 'target_blankmentona',
 'designation',
 '23story',
 'conservationist',
 'juniper',
 'snaefells',
 'coming',
 'abdulaziz',
 'frenchalgerian',
 'indepth',
 'powder',
 'dwellers',
 'flayed',
 'cygnus',
 'instructional',
 'halloween',
 'strips',
 'ottesen',
 'dardanelles',
 'deflect',
 'afraid',
 'brusha',
 'pathway',
 'takeout',
 'waxmaker',
 'harbors',
 'settlement',
 'jalisco',
 'continues',
 'keeping',
 'lerner',
 'explosions',
 'orangey',
 'foulmouthed',
 'pungent',
 'battling',
 '19year',
 'sportsmans',
 'symphonie',
 'infantile',
 'winniethepoohs',
 'injuries',
 'durers',
 'goodlooking',
 'hrefhttpwwwjarchivecommedia20060515_j_23jpg',
 'gosudarstvennoy',
 'target_blankpaintinga',
 'crossword',
 '[trebeksmade',
 'hrefhttpwwwjarchivecommedia20060406_j_15jpg',
 'falsies',
 'thornhill',
 'spruce',
 'silkworms',
 'hrefhttpwwwjarchivecommedia20060601_j_24ajpg',
 'cleats',
 'preying',
 'hrefhttpwwwjarchivecommedia20080509_dj_14jpg',
 'renaldo',
 'invadee',
 'courtesan',
 'happening',
 'amazed',
 'system',
 'fanciest',
 'bridalveil',
 'politicians',
 'eulogized',
 'certain',
 'musicals',
 'obstructionary',
 'shingles',
 'spectacled',
 'contrasting',
 'thickskulled',
 'sklodowska',
 'kissinger',
 'island',
 'millionfooted',
 'famosos',
 'zoltan',
 'agatha',
 'nicodemus',
 'demeanour',
 'suddenly',
 'alluring',
 'bullseye',
 'sleepy',
 'memoryloss',
 'avenged',
 'pattens',
 'umberto',
 'arollin',
 'sagittarian',
 'chunks',
 'verrocchio',
 'malloy',
 'robbing',
 'tangomarkkinat',
 'tanqueray',
 'oneact',
 'kidtested',
 'hepatitis',
 'squaring',
 'canaima',
 'psychiatric',
 'failsfor',
 'hrefhttpwwwjarchivecommedia20091117_dj_27jpg',
 'tranquility',
 'transcripts',
 'serling',
 'hudson',
 'me_i_wont_reply',
 'frontman',
 'widowa',
 'denomination',
 'hsub2subsosub4sub',
 'bottle',
 'storage',
 'bloodied',
 '179495',
 'hrefhttpwwwjarchivecommedia20070221_j_16jpg',
 'sculptors',
 'kinging',
 'malted',
 'schmitz',
 'ukuleles',
 'smallest',
 'everything',
 'negotiated',
 'shrine',
 'predicts',
 'braced',
 'novelty',
 'pepsico',
 'equalize',
 'hrefhttpwwwjarchivecommedia20080313_dj_30ajpg',
 'regrette',
 'aldonza',
 'grantdeborah',
 'poughkeepsie',
 'teheran',
 'durnstein',
 'anemia',
 'celsius',
 'funakoshi',
 'evercool',
 'conducting',
 'cleary',
 'crusoe',
 'magnet',
 'budding',
 'ambulanceone',
 'toadstool',
 'diminutive',
 'onstage',
 'galaxys',
 'dreiser',
 'formeda',
 'warren',
 'from1978',
 'scroll',
 'legends',
 'indoors',
 'yearcrossing',
 'bethlehem',
 'hrefhttpwwwjarchivecommedia20080416_j_12jpg',
 'second',
 'thinghe',
 'fragile',
 'astigmatism',
 'daltreys',
 'weatherman',
 'brownishorange',
 'algeria',
 '550squaremile',
 'technicolor',
 'superlative',
 'dorsey',
 'tajikistan',
 'nightmare',
 'crosses',
 'escapes',
 'fibers',
 'officea',
 'peppermint',
 'snowglobe',
 'persia',
 'krispy',
 'tender',
 'prohibited',
 'inquire',
 'english',
 'unimak',
 'installation',
 'schnitzler',
 'ericsons',
 'environmental',
 'retsyn',
 'inscribed',
 'hrefhttpwwwjarchivecommedia20100506_j_18wmvthesea',
 'composing',
 'mulukhiya',
 'midocean',
 'henares',
 'answer',
 'hrefhttpwwwjarchivecommedia20060725_dj_24wmvkelly',
 'besant',
 'seacolored',
 'hrefhttpwwwjarchivecommedia20080509_dj_17jpg',
 'dishes',
 'landlocked',
 'domenico',
 'marconi',
 'physicsa',
 'received',
 'effects',
 'propagandist',
 'hutchinson',
 'hrefhttpwwwjarchivecommedia20070112_j_30jpg',
 'blockbuster',
 'saltwatera',
 'offbroadway',
 'garrett',
 'lymphoid',
 'poulet',
 'zambezi',
 'lofting',
 'peninsular',
 'modifying',
 'pulaski',
 'hrefhttpwwwjarchivecommedia20110422_dj_18jpg',
 'novice',
 'prudent',
 'involving',
 'tootsie',
 'cocktailswilling',
 'bruxomania',
 'country',
 'tambora',
 'triskaidekaphobic',
 'todhunter',
 'enzyme',
 'secularism',
 'penalty',
 'stretched',
 'dorsay',
 '125000',
 'metaphor',
 'downstream',
 'jewels',
 'gyalpo',
 'constantinescu',
 'kathrine',
 'spitzer',
 'businesses',
 'lowkey',
 'effort',
 'retarding',
 'telescopeeyed',
 'naders',
 'starflyer',
 'trueba',
 'campout',
 'crayon',
 'icelandic',
 'hardened',
 'mummys',
 'trends',
 'exercisea',
 'allstar',
 'fundraising',
 'exited',
 'mollusk',
 'coffin',
 'dudley',
 'connections',
 'hrefhttpwwwjarchivecommedia20040521_j_26jpg',
 'forewarned',
 'punched',
 'protests',
 'roseus',
 'hubert',
 'wrecks',
 'torment',
 'orbits',
 'maggini',
 'applying',
 'deluge',
 'romancing',
 'isreala',
 'airlines',
 'patients',
 'alexakis',
 'bernadotte',
 'georgiapacific',
 'rimini',
 'sanctimonious',
 'teenaer',
 'undulation',
 'picasso',
 'pastorelli',
 'mengers',
 '797802',
 'plumage',
 'forceful',
 'hrefhttpwwwjarchivecommedia20041111_j_08jpg',
 'brandeis',
 'hrefhttpwwwjarchivecommedia20001003_dj_14jpg',
 'hrefhttpwwwjarchivecommedia20100125_j_25bjpg',
 'alaskas',
 'vojvode',
 'hrefhttpwwwjarchivecommedia20071113_dj_07jpg',
 'highspeed',
 'deutschland',
 'target_blank2000',
 'californianus',
 'apuleius',
 'removing',
 'wafers',
 'tippecanoe',
 'kristy',
 'prosecutor',
 'africanamericans',
 'clinics',
 'hrefhttpwwwjarchivecommedia20050629_dj_29jpg',
 'junior',
 'dreams',
 'therapy',
 'tilsit',
 'longbaughs',
 'starry',
 'content',
 'tributary',
 'relentless',
 'valparaiso',
 'straight',
 'inhabitant',
 'jerseyborn',
 'comparative',
 'hrefhttpwwwjarchivecommedia20071203_dj_30jpg',
 'caesar',
 'rustic',
 'autonomous',
 'endearing',
 'originates',
 'englishman',
 'metropolis',
 'jeanclaude',
 'probably',
 'madeira',
 'collect',
 'cousins',
 'cornish',
 'parachutists',
 'goodnight',
 'molten',
 'historian',
 'target_blankhereacontroversial',
 'discorific',
 'ataturk',
 'serene',
 'saturated',
 'sammler',
 'markets',
 '13000th',
 'schmitt',
 'pollinated',
 'wright',
 'azimuth',
 '2syllable',
 'cruncher',
 'presbytery',
 'recalls',
 '6wicket',
 'embodies',
 'steaki',
 'brookline',
 'duarte',
 'pensacola',
 'lighters',
 'suburban',
 'knowsi',
 'legislature',
 'oxfords',
 '19051926',
 'target_blankcloseup',
 'polystyrene',
 'laureate',
 'lustbader',
 'utopia',
 'islahiye',
 '10sup43sup',
 'leader',
 'someday',
 'hometown',
 'doggie',
 'cashed',
 'hrefhttpwwwjarchivecommedia20040707_j_13jpg',
 'psychoanalytic',
 'labrador',
 'decided',
 'manned',
 'propellor',
 'mcclellans',
 'clement',
 'goofus',
 'wieslander',
 'cooperate',
 'spring',
 'deluxe',
 'nikita',
 'angela',
 'skatera',
 'ibanez',
 'prison',
 'pomelo',
 'mariana',
 'overtake',
 'harrelsons',
 'columbines',
 'primavera',
 'griefs',
 'hrefhttpwwwjarchivecommedia20070222_dj_06jpg',
 'horatio',
 'expenditures',
 'structural',
 'supernova',
 'torino',
 'hunters',
 'newtonjohn',
 'crosby',
 'transfer',
 'cathode',
 'howards',
 'soiled',
 'secretary',
 'rubythroated',
 'target_blankfamous',
 'henrycharles',
 'refrigerated',
 'raquel',
 'chanakyapuri',
 'toreador',
 'honored',
 'transits',
 'hrefhttpwwwjarchivecommedia20070222_j_18jpg',
 'dimaggios',
 'stormen',
 'expire',
 'screenwriting',
 'without',
 'crimebased',
 'handey',
 'doffed',
 'allegheny',
 'fultonbuilt',
 'appoint',
 'groans',
 'selleck',
 'cocktail',
 'clericuzio',
 'bonfire',
 'indestructible',
 'highranking',
 'goldwyn',
 'hrefhttpwwwjarchivecommedia20080722_dj_26wmvsarah',
 'hatcher',
 'temperatures',
 'kittery',
 'varying',
 'zealand',
 'ruthless',
 'confirmed',
 'zacharias',
 'taller',
 'nnegroes',
 'francoprussian',
 'alcala',
 'boleslaw',
 'hrefhttpwwwjarchivecommedia20111021_dj_30jpg',
 'catagorizing',
 'mozarts',
 'countryside',
 'lightning',
 'hofburg',
 'energies',
 'expansion',
 'pinter',
 'creates',
 'rifles',
 'exciting',
 'gerald',
 'accesses',
 'national',
 'ladyinwaiting',
 'mccalls',
 'manhattan',
 'ethnobotany',
 'busting',
 'things',
 'annulled',
 'handel',
 'pepperdines',
 '191618',
 'alaska',
 'firewood',
 'cruelty',
 'brahma',
 'minting',
 'decatur',
 'carnivorous',
 'woolsey',
 'plucking',
 '6pointed',
 'terribles',
 'infant',
 'widest',
 'crisscross',
 'helmet',
 'unconquering',
 'rhapsodies',
 'economists',
 'exhale',
 'braids',
 'belleville',
 'punishments',
 'spearlike',
 'manipulate',
 'trodden',
 'acadians',
 'virttex',
 'hrefhttpwwwjarchivecommedia20080408_j_10ajpg',
 'descends',
 'showrooma',
 'distinction',
 'obviously',
 'hrefhttpwwwjarchivecommedia20090514_dj_24wmvthesea',
 'ubiquinone',
 'coating',
 'morningstar',
 'alexandria',
 'bubble',
 'heinlein',
 'speeding',
 'different',
 'attached',
 'homemakers',
 'involvement',
 'ureters',
 'shoeless',
 'luther',
 'rannulph',
 'violated',
 'hrefhttpwwwjarchivecommedia19980922_j_15wmvherea',
 'builtin',
 'cultivating',
 'oftcovered',
 'topographical',
 'rattle',
 'slumlord',
 'eratosthenes',
 'requesting',
 'hrefhttpwwwjarchivecommedia20110330_dj_30jpg',
 'stringing',
 'coasts',
 'embolus',
 'murdering',
 'parchment',
 'uninhabitable',
 'cryogenic',
 'soundtrack',
 'designing',
 'mercader',
 'dumplings',
 'planetary',
 '550you',
 'fleecy',
 'atkinson',
 'sewing',
 'moderated',
 'singeractor',
 'hrefhttpwwwjarchivecommedia20050629_dj_18jpg',
 'frusciante',
 'feature',
 'lauder',
 'grovers',
 'grounda',
 'iseinfeldi',
 'richardson',
 'interzone',
 'presides',
 'crudites',
 'burrow',
 'walkinshaw',
 'pardalis',
 'peanut',
 'highly',
 'centuries',
 'zealander',
 'hating',
 'troupes',
 'geology',
 'israela',
 'supposed',
 'deville',
 'quixote',
 'appearance',
 'pfennigs',
 'stoeckl',
 'dyeing',
 'liddell',
 'apparently',
 'willow',
 'aurifex',
 'retronyms',
 'zihuatanejo',
 'snatched',
 'irrigated',
 'oneida',
 'clayand',
 'spanisharchitecture',
 'kopecks',
 'rapper',
 'splitting',
 'warlock',
 'renaming',
 'hotshot',
 'photojournalist',
 'mesabi',
 'unflattering',
 'laurent',
 'psycho',
 'pioneering',
 'kidneys',
 'warfare',
 'pythons',
 'supporter',
 'wimpole',
 'levitate',
 'jolson',
 'huizong',
 'competitor',
 'archbishop',
 'hrefhttpwwwjarchivecommedia20101207_j_28ajpg',
 'statements',
 'accumulation',
 'unabbreviated',
 'sputnik',
 'websters',
 'kermit',
 'repetitive',
 'inhabitants',
 'hardhearted',
 'greening',
 'mcluhan',
 'constructing',
 'doughnuts',
 'esterhaus',
 'glandular',
 'payroll',
 'cyrillic',
 'ronnies',
 'hemingways',
 'lending',
 'reporter',
 'desired',
 'devoted',
 'tournament',
 'koenigsburg',
 'lexington',
 'granting',
 'mythological',
 'alexanders',
 'chairs',
 'godunov',
 'target_blankrisesa',
 'loreal',
 'phoenixa',
 'mourned',
 'newsmakers',
 'schiffer',
 'amnesty',
 'figments',
 'myocardial',
 'dendur',
 'montalban',
 'hakuna',
 'proves',
 'appointee',
 'branson',
 'tolerance',
 '19791989',
 'military',
 'clapping',
 'majorca',
 'infielder',
 'succeed',
 'ransom',
 'devastating',
 'oldest',
 'mcclain',
 'harvest',
 'emoticon',
 'altostratus',
 'dodona',
 'riddick',
 'meadows',
 'concepts',
 'gallery',
 'josephs',
 'isclose',
 'hrefhttpwwwjarchivecommedia20090929_j_29jpg',
 'aurally',
 'sleeper',
 'uncontrollable',
 'committees',
 'halfsisters',
 'hrefhttpwwwjarchivecommedia20041109_dj_11jpg',
 'orpheus',
 'filling',
 'reflected',
 'selects',
 'punish',
 'flared',
 'protons',
 'lantern',
 'wharves',
 'nixons',
 'theyre',
 'aggressive',
 'kennesaw',
 'amiodarone',
 'antonio',
 'flattened',
 'funerals',
 '9yearold',
 'traumatized',
 'hrefhttpwwwjarchivecommedia20050315_j_08jpg',
 'goldilocks',
 'toothed',
 'sleeveless',
 'concord',
 'descended',
 'carrey',
 'robinsonade',
 'mimicking',
 'hrefhttpwwwjarchivecommedia19991217_j_21jpg',
 'potatoes',
 'tickle',
 'armysounding',
 'lasting',
 'shapeless',
 'dockside',
 'fanfare',
 'aesops',
 'blackeyed',
 'typewriter',
 'latvias',
 'minoxidil',
 'perambulator',
 'stiles',
 'monstrous',
 'savion',
 'nonconductors',
 'fearful',
 'tigran',
 'quaternary',
 'rented',
 'directive',
 'connected',
 'simmons',
 'stadiun',
 'illegitimate',
 'savior',
 'exaggerated',
 'princessia',
 'testorf',
 'cutthroat',
 'exotic',
 'occurrence',
 'morrison',
 'freemason',
 'milwaukee',
 'salinger',
 'splash',
 'citizens',
 'beeswax',
 'melita',
 'broccoli',
 'teutul',
 'chewed',
 'material',
 'englanders',
 'sweeper',
 'supplied',
 'suggested',
 'bartok',
 'adrian',
 'displays',
 'target_blankpaintingsa',
 'dissatisfied',
 'maniac',
 'preach',
 'cooperations',
 'wetlands',
 'sheffields',
 'darkened',
 'nuestro',
 'crusher',
 'hrefhttpwwwjarchivecommedia20071113_j_25jpg',
 '20person',
 'heaters',
 'version',
 'outgrossing',
 'timbers',
 'readjustment',
 'clients',
 'fantine',
 'diminuitive',
 'lifeboat',
 'alienating',
 'lindsay',
 'selfappointed',
 'retronm',
 'unimpeded',
 'nephew',
 'invading',
 'edible',
 'hrefhttpwwwjarchivecommedia20080926_dj_27ajpg',
 'random',
 'punjab',
 'tempest',
 'haitis',
 'layzie',
 'bening',
 'housekeeper',
 'manitou',
 'phosphate',
 'variation',
 'hrefhttpwwwjarchivecommedia20050315_dj_18jpg',
 'fauntroya',
 'lombard',
 'tenure',
 'mormon',
 'hrefhttpwwwjarchivecommedia20060515_j_13jpg',
 'lumpur',
 'membership',
 'patron',
 'refugee',
 'pamphlet',
 'enzymes',
 'campbells',
 'perversion',
 'arteryclogging',
 'interstellar',
 'orlando',
 'shunya',
 'amulets',
 'storming',
 'skidmore',
 'stadsholmen',
 '51milelong',
 'foreigners',
 'greater',
 'mettemarit',
 '6pronged',
 'pebbles',
 'brennan',
 'cherie',
 'eurasian',
 'pounding',
 'motorcycle]',
 'casbah',
 'stressed',
 'loathing',
 'radios',
 'hrefhttpwwwjarchivecommedia20080310_dj_19ajpg',
 'itinerary',
 'gastropods',
 'nutrilite',
 'elephants',
 'musthaves',
 'cyclical',
 '19391960',
 'recoup',
 'plastron',
 'pioneered',
 'caught',
 'boutiques',
 'undreamed',
 'slugger',
 'hrefhttpwwwjarchivecommedia20080508_j_21mp3isampleia',
 'eisenach',
 'blocked',
 'starves',
 'mojave',
 'pointiest',
 'walpoles',
 'moonlight',
 'wahlberg',
 'accountants',
 'icebergs',
 'adapted',
 'copied',
 'yorkvermont',
 'assume',
 'steeple',
 'communisthunting',
 'towering',
 'prevention',
 'auctioned',
 'amontillado',
 'assignee',
 'enlisted',
 'crownofthorns',
 'carolina',
 'bangladeshs',
 'mellon',
 'coppola',
 'photographer',
 'assistant',
 'solutions',
 'inflation',
 ...}

# Applying the chisquared test

In [69]:
from scipy.stats import chisquare
import numpy as np

high_value_count = jeopardy[jeopardy['high_value'] == 1].shape[0] # get the count from this mask
low_value_count = jeopardy[jeopardy['high_value'] == 0].shape[0] # get the count from this mask

In [70]:
high_value_count

5734

In [71]:
low_value_count

14265

In [72]:
chi_squared = []

In [73]:
for observ in observed_expected:
    total = sum(observ)
    total_prop = total / jeopardy.shape[0]
    high_value_expected = total_prop * high_value_count
    low_value_expected = total_prop * low_value_count
    observed = np.array([observ[0],observ[1]])
    expected = np.array([high_value_expected,low_value_expected])
    chi_squared.append(chisquare(observed,expected))

chi_squared

[Power_divergenceResult(statistic=2.1177104383031944, pvalue=0.14560406868264344),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.255049337875229, pvalue=0.6135419116911882),
 Power_divergenceResult(statistic=4.97558423439135, pvalue=0.025707519787911092),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469)]

# Chi squared results

There is not a significance in terms used in the sample between high value and low value rows.  Only 1 term had a frequency higher than 5 which makes the chi squared test not useful here.  It would be better to run the test with terms that have higher frequencies